name: CI Build

on:
  schedule:
    - cron: 0 5 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: pwd
      - name: Run a multi-line script
        run: |
          ls
          git status
      - name: Save current data
        run: |
          FILE=./public/assets/data/`date --date="1 day ago" +"%Y%m%d"`.json
          if [ -f "$FILE" ]; then
              echo "$FILE exists. Done for today."
          else
              echo "Begin to get today's data."
              url="https://services1.arcgis.com/CY1LXxl9zlJeBuRZ/arcgis/rest/services/Florida_COVID19_Cases/FeatureServer/0/query?f=json&where=T_positive%20IS%20NOT%20NULL&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&orderByFields=T_positive%20desc&outSR=102100&resultOffset=0&resultRecordCount=67&cacheHint=true"
              response=$(curl -f "$url")
              status=$?
              if [ $status -eq 0 ]; then
                  echo $response > $FILE
                  echo "$FILE saved."
                  echo `date --date="1 day ago" +"%Y%m%d"` >> ./public/assets/data.txt
              else
                  echo "curl exit code: ($status) $response"
                  exit $status
              fi
          fi
      - name: Save current tampa data
        run: |
          FILE=./public/assets/data/tampa-`date --date="1 day ago" +"%Y%m%d"`.json
          if [ -f "$FILE" ]; then
              echo "$FILE exists. Done for today."
          else
              echo "Begin to get today's data."
              url="https://services1.arcgis.com/CY1LXxl9zlJeBuRZ/arcgis/rest/services/Florida_COVID19_Cases/FeatureServer/0/query?f=json&where=OBJECTID%20=%2020&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&orderByFields=T_positive%20desc&outSR=102100&resultOffset=0&resultRecordCount=67&cacheHint=true"
              response=$(curl -f "$url")
              status=$?
              if [ $status -eq 0 ]; then
                  echo $response > $FILE
                  echo "$FILE saved."
                  echo tampa-`date --date="1 day ago" +"%Y%m%d"` >> ./public/assets/tampa-data.txt
              else
                  echo "curl exit code: ($status) $response"
                  exit $status
              fi
          fi
      - name: Save current state data
        run: |
          FILE=./public/assets/data/state-`date --date="1 day ago" +"%Y%m%d"`.json
          if [ -f "$FILE" ]; then
              echo "$FILE exists. Done for today."
          else
              echo "Begin to get today's data."
              url="https://services1.arcgis.com/CY1LXxl9zlJeBuRZ/arcgis/rest/services/Florida_COVID19_Cases/FeatureServer/0/query?f=json&where=1%3D1&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&outStatistics=%5B%7B%22statisticType%22%3A%22sum%22%2C%22onStatisticField%22%3A%22FLResDeaths%22%2C%22outStatisticFieldName%22%3A%22Deaths%22%7D%2C%7B%22statisticType%22%3A%22sum%22%2C%22onStatisticField%22%3A%22T_positive%22%2C%22outStatisticFieldName%22%3A%22Positive%22%7D%2C%7B%22statisticType%22%3A%22sum%22%2C%22onStatisticField%22%3A%22C_Hosp_Yes%22%2C%22outStatisticFieldName%22%3A%22Hospitalized%22%7D%2C%7B%22statisticType%22%3A%22sum%22%2C%22onStatisticField%22%3A%22T_total%22%2C%22outStatisticFieldName%22%3A%22TotalTests%22%7D%2C%7B%22statisticType%22%3A%22sum%22%2C%22onStatisticField%22%3A%22T_negative%22%2C%22outStatisticFieldName%22%3A%22Negative%22%7D%2C%7B%22statisticType%22%3A%22sum%22%2C%22onStatisticField%22%3A%22TPending%22%2C%22outStatisticFieldName%22%3A%22Pending%22%7D%5D&outSR=102100&cacheHint=true"
              response=$(curl -f "$url")
              status=$?
              if [ $status -eq 0 ]; then
                  echo $response > $FILE
                  echo "$FILE saved."
                  echo state-`date --date="1 day ago" +"%Y%m%d"` >> ./public/assets/state-data.txt
              else
                  echo "curl exit code: ($status) $response"
                  exit $status
              fi
          fi
      - name: git check in
        env:
          GIT_OWNER_EMAIL: ${{ secrets.GIT_OWNER_EMAIL }}
          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: |
          git config user.email "$GIT_OWNER_EMAIL"
          git config user.name "NickStees"
          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -a -m "add weather data"
            git remote rm origin
            git remote add origin https://NickStees:$PUSH_TOKEN@github.com/NickStees/covid-19-florida-historic-data.git
            git push origin HEAD:master
          else
            echo 'unable to detech changes'
          fi
